name: Nightly build
"on":
  schedule:
    - cron: 00 0 * * *
  push:
    branches:
      - nightly-build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build --if-present -- --token ${{ secrets.GITHUB_TOKEN }}
      - run: npm test --if-present
      - name: Create out dir
        run: mkdir out
      - name: Pack
        run: npm pack --pack-destination out
      - name: Get version name
        id: getv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
      - name: Echo version name
        run: echo "${{ steps.getv.outputs.content }}"
      - name: Get releace id
        id: release
        run: |
          out=$(node -e 'var parsed = JSON.parse("${{ vars.RUN_NUMBERS }}"); var ver = "${{steps.getv.outputs.content}}"; if(typeof parsed[ver] == "undefined"){parsed[ver] = 0} parsed[ver]++; process.stdout.write(parsed[ver] + "|" + JSON.stringify(parsed));')
          IFS='|' read -ra split <<< "$out"
          gh variable set RUN_NUMBERS --body ${out[1]}
          echo "version=${out[0]}" >> $GITHUB_OUTPUT
      - name: Create a release
        id: new_release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.getv.outputs.content }}build${{ steps.release.outputs.version }}"
          name: "Release nightly #${{ github.run_number }}"
          body: |
            A untested nightly release
            - For testing
          prerelease: true
          artifacts: "out/*"
