name: Nightly build
'on':
  schedule:
    - cron: 00 0 * * *
  push:
    branches:
      - nightly-build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
      - name: Create out dir
        run: mkdir out
      - name: Pack
        run: npm pack --pack-destination out
      - name: Get version name
        id: get_v
        uses: juliangruber/read-file-action@v1
        with:
          path: "version.txt"
      - name: Create a release
        id: new_release
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ steps.read_file.outputs.contents }}'
          name: 'Release nightly_${{ steps.read_file.outputs.contents }}alpha'
          body: |
            A untested nightly release
            - For testing
          prerelease: true
          skipIfReleaseExists: true
          artifacts: "out/**"
