name: Nightly build
'on':
  schedule:
    - cron: 00 0 * * *
  push:
    branches:
      - nightly-build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present
      - name: Pack
        run: npm pack --pack-destination out
      - name: Create a release
        id: new_release
        uses: ncipollo/release-action@v1
        with:
          tag: 'Nightly${{ github.run_number }}'
          release_name: 'Release nightly_${{ github.run_number }}alpha'
          body: |
            A untested nightly release
            - For testing
          prerelease: true
          skipIfReleaseExists: true
          artifacts: "out/**"
